feature_net_kwargs:
  rgb_feat:
    cls: DummyImgFeat
    output_dim: 512
    image_model: mineclip # Image models: mineclip, gdino
  compass:
    cls: CompassMLP
    input_dim: 4
    hidden_dim: 128
    output_dim: 128
    hidden_depth: 2
  gps:
    cls: GPSMLP
    hidden_dim: 128
    output_dim: 128
    hidden_depth: 2
  # voxels:
  #   cls: FlattenedVoxelBlockEncoder
  #   embed_dim: 8
  #   hidden_dim: 128
  #   output_dim: 128
  #   hidden_depth: 2
  # biome_id:
  #   cls: BiomeIDEmb
  #   embed_dim: 8
  # prev_action:
  #   cls: PrevActionEmb
  #   embed_dim: 8
  # prompt:
  #   cls: PromptEmbFeat
  #   output_dim: 512

feature_fusion:
  output_dim: 512
  hidden_depth: 0

actor:
  hidden_dim: 256
  hidden_depth: 3

critic:
  hidden_dim: 256
  hidden_depth: 3

mineclip:
  arch: "vit_base_p16_fz.v2.t2"
  hidden_dim: 512
  image_feature_dim: 512
  mlp_adapter_spec: "v0-2.t0"
  pool_type: "attn.d2.nh8.glusw"  # filled by variant
  resolution: [160, 256]
  ckpt:
    path:  /home/kenjic/documents/MineDojo_PPO/weights/attn.pth # filled by users
    checksum: "b5ece9198337cfd117a3bfbd921e56da"

env:
  task: "milk a cow"
  num_envs: 4

agent:
  total_timesteps: 8000
  num_steps: 1000
  num_minibatches: 1
  learning_epochs: 1
  clip_vloss: false
  return_norm: false
  gamma: 0.99
  gae_lambda: 0.95
  seed: 1
  clip_coef: 0.2
  learning_rate: !!float 1e-4
  min_lr: !!float 1e-6
  ent_coef: 0.005
  vf_coef: 0.5
  max_grad_norm: 10
  target_kl: 0.015

debug: false

ppo_buffer:
  buffer_size: 15000
  number_actions: 89

si_buffer:
  buffer_size: 50
  buffer_mean: 0.1
  buffer_std: 0
  buffer_delta: 0

hyperparameters:
  task: "milk a cow"
  epochs: 20
  batch_size: 5000

  video_min_rew: 32

  load_checkpoint: false
  checkpoint_dir: "/home/user/Mine/results/run_231109_0814/weights"
  checkpoint_epoch: 0

  imitation_learning: false
  demos_path: ""
  
  file_logging: true
  wandb_init: true


# hydra: 
#   job:
#     chdir: true
#   run:
#     dir: .
#   output_subdir: null